### ISSUE TITLE
mesh_smoothing of gmsh file removes information about tags

### ISSUE THREAD

**Issue by bonh** [nschloe/voropy#10]
Before mesh_smoothing the Elements part in *.msh file looks like this:
`$Elements
1 1 2 1 3 1 9
`
with 7 numbers.

After mesh_smoothing it looks like this:
`$Elements
1 2 0  1 9 7764`
with only 6 numbers

From http://www.manpagez.com/info/gmsh/gmsh-2.2.6/gmsh_63.php:
`elm-number elm-type number-of-tags < tag > … node-number-list`
So it seems, as if the number-of-tags is set to zero and the tag info is removed.

**Comment by nschloe** [comment]
Good call. I'll look at this later.

**Comment by nschloe** [comment]
Fixed now.
