### ISSUE TITLE
vestigial dependence on matplotlib

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/voropy#27]
While looking into nschloe/meshio#210, which depends on pygmsh, I found that
```python
import pygmsh
```
raised
```
ModuleNotFoundError: No module named 'matplotlib'
```

It turns out to be due to pygmsh's dependency on voropy so `import voropy` raises the same error. 

The problematic module seems to be voropy/smoothing.py.

Suspicion falls on the recent commit 4be52d1095f5ea1089e5e8da2563b5c242bbd2e0 ‘make matplotlib dependency optional’.

**Comment by nschloe** [comment]
Closing via PR #28.
